linux:
  hosts: graylog

windows:
  hosts: dc01 elan-winhost-01 elan-winsrv-01
  vars:
    ansible_user: "{{ windows.ansible_user }}"
    ansible_password: "{{ windows.ansible_password }}"
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore

domain_controllers:
  hosts:
    dc01:
      ansible_host: 10.10.20.254

  vars:
    ansible_user: "{{ windows.ansible_user }}"
    ansible_password: "{{ windows.ansible_password }}"
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore

domain_members:
  hosts:
    elan-winhost-01:
      ansible_host: 10.10.20.32

    elan-winsrv-01:
      ansible_host: 10.10.20.16

dns_server:
  hosts:
    elan-winsrv-01:
      ansible_host: 10.10.20.32
