## Downloads and installs Sysmon

- name: Download Sysmon Zip from URL
  ansible.windows.win_get_url:
    url: https://download.sysinternals.com/files/Sysmon.zip
    dest: C:\sysmon.zip

- name: Unzip the Sysmon Zip File
  community.windows.win_unzip:
    src: C:\sysmon.zip
    dest: C:\sysmon
    delete_archive: yes

- name: Clone Olaf's Sysmon Modular Configurations
  ansible.windows.win_get_url:
    url: https://github.com/olafhartong/sysmon-modular/archive/refs/heads/master.zip
    dest: C:\sysmon-modular.zip

- name: Unzip the Sysmon Config Zip
  community.windows.win_unzip:
    src: C:\sysmon-modular.zip
    dest: C:\\
    delete_archive: yes

- name: Merge all the configs into one file
  ansible.windows.win_shell: |
    . .\Merge-SysmonXml.ps1
    Merge-AllSysmonXml -Path ( Get-ChildItem '[0-9]*\*.xml') -AsString | Out-File sysmonconfig.xml
  args:
    chdir: C:\sysmon-modular-master

- name: Install Sysmon Configuration
  ansible.windows.win_shell: C:\sysmon\sysmon64.exe -accepteula -i C:\sysmon-modular-master\sysmonconfig.xml

- name: Remove Sysmon Directory
  ansible.windows.win_file:
    path: C:\sysmon
    state: absent

- name: Remove Sysmon Modular Directory
  ansible.windows.win_file:
    path: C:\sysmon-modular-master
    state: absent
