- name: Install/configure Dependencies for Elastic
  hosts: elastic
  tasks:
    #todo: move this one to main or something, this is just for testing
    - name: Update apt package repo
      become: true
      apt:
        #not running upgrade so there aren't any surprises with new packages or dependencies.
        # this is obviously not the most secure, but that's sort of the point
        #upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day
    - name: Install gnupg2
      apt:
        name: gnupg2
        state: present


- name: Generate Snakeoil Certs
  hosts: localhost
  tasks:
    - name: gencerts
      shell: |
        openssl req -x509 -nodes -days 3650 -newkey EC -pkeyopt ec_paramgen_curve:secp521r1 -keyout /etc/ssl/private/ssl-cert-snakeoil.key -out /etc/ssl/certs/ssl-cert-snakeoil.pem -subj "/C=US/ST=Nuuuuuuu yawk/L=rock /O=fizzy wizzy electrocity/OU=code/CN=red/emailAddress=gidooo@mail.rit.edu"

- name: Configure Elasticsearch Master
  hosts: elasticmaster
  roles:
    - { role: elasticsearch, es_instance_name: "{{ inventory_hostname }}", es_heap_size: "3072M", es_config: {network.host: "0.0.0.0", http.port: 9200, transport.port: 9300, node.data: false, node.master: true, cluster.initial_master_nodes: "{{ inventory_hostname }}", xpack.security.enabled: false} }
  vars:
   # es_enable_http_ssl: true
  #  es_api_basic_auth_username: elastic
    #todo: set this in an intelligent way
  #  es_api_basic_auth_password: changeme
   # es_ssl_key: /etc/ssl/private/ssl-cert-snakeoil.key
  #  es_ssl_certificate: /etc/ssl/certs/ssl-cert-snakeoil.pem


- name: Configure Elasticsearch Data Nodes
  hosts: elasticdata
  roles:
    - { role: elasticsearch, es_instance_name: "{{ inventory_hostname }}", es_heap_size: "3072M", es_config: {network.host: "0.0.0.0", discovery.zen.ping.unicast.hosts: "10.10.40.201:9300", http.port: 9200, transport.port: 9300, node.data: true, node.master: false,  xpack.security.enabled: false} }
  vars:
  #  es_enable_http_ssl: true
  #  es_api_basic_auth_username: elastic
    #todo: set this in an intelligent way
  #  es_api_basic_auth_password: changeme
  #  es_ssl_key: /etc/ssl/private/ssl-cert-snakeoil.key
  #  es_ssl_certificate: /etc/ssl/certs/ssl-cert-snakeoil.pem


- name: Finish Elastic install
  ansible.builtin.import_playbook: installelastictasks.yml