- name: Install Elasticsearch
  hosts: elastic
  become: true

  tasks:
    - name: Add Ansible SSH key
      authorized_key:
        user: root
        key: "{{ lookup('file', '~/.ssh/id_elastic.pub') }}"
        state: present
