- name: "Main playbook that executes subplaybooks"
  hosts: localhost linux
  #apply linux role to localhost
  tasks:
  - include_role: 
      name: linux


  
- name: "Create users"
  ansible.builtin.import_playbook: generateusers.yml

- name: "Generate ssh keys"
  ansible.builtin.import_playbook: generatesshkeys.yml

- name: "Run graylog playbook"
  ansible.builtin.import_playbook: installgraylog.yml

#FINAL PLAYBOOK: Set SSH keys to be not-bootstrap
- name: "Run setsshkeys playbook"
  ansible.builtin.import_playbook: setsshkeys.yml
