- name: Set SSH keys to be not-bootstrap
  hosts: localhost
  become: true

  tasks:
    # set graylog ssh key to id_graylog in .ssh/config
    - name: set graylog ssh keys
      community.general.ssh_config:
        user: root
        host: "graylog"
        identity_file: "/root/.ssh/id_graylog"
        state: present