- name: Install Elasticsearch
  hosts: elastic
  become: true

  tasks:
    - name: Install gnupg2
      apt:
        name: gnupg2
        state: present

    - name: Add Elasticsearch GPG key
      apt_key:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        state: present

    - name: Add Elasticsearch APT repository
      apt_repository:
        repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main
        state: present

    - name: Install Elasticsearch
      apt:
        name: elasticsearch
        state: present

    - name: Start Elasticsearch service
      service:
        name: elasticsearch
        state: started
        enabled: true

    - name: Add Ansible SSH key
      authorized_key:
        user: root
        key: "{{ lookup('file', '~/.ssh/id_elastic.pub') }}"
        state: present
